#
## Segment 1 - Using NumPy to perform arithmetic operations on data

In [ ]:
import numpy as np
from numpy.random import randn

In [ ]:
np.set_printoptions(precision=2)

## Creating arrays
### Creating arrays using a list

In [ ]:
a = np.array([1,2,3,4,5,6])
a

In [ ]:
b = np.array([[10,20,20],[40,50,60]])
b

In [ ]:
np.random.seed(25)
c = 36*np.random.randn(6)
c

In [ ]:
d = np.arange(1, 35)
d

In [ ]:
a*10

In [ ]:
c + a

In [ ]:
c-a

In [ ]:
c*a

In [ ]:
c/a

### Multiplying matrices and basic linear algebra

In [ ]:
aa = np.array([[2.,4.,6.],[1.,3.,5.],[10.,20.,30.]])
aa

array([[ 2.,  4.,  6.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [ ]:
bb = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
bb

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
aa*bb

array([[  0.,   4.,  12.],
       [  3.,  12.,  25.],
       [ 60., 140., 240.]])

In [ ]:
np.dot(aa,bb)

array([[ 48.,  60.,  72.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])